export enum ActionType {
    REQUEST_CRUNCHYROLL_HISTORY,
    STORE_CRUNCHYROLL_HISTORY,
    ERROR_CRUNCHYROLL_HISTORY,

    REQUEST_CRUNCHYROLL_SESSION,
    STORE_CRUNCHYROLL_SESSION,

    REQUEST_TRAKT_SEARCH,
    STORE_TRAKT_SEARCH,

    REQUEST_TRAKT_EPISODE_HISTORY,
    STORE_TRAKT_EPISODE_HISTORY
}