export enum ActionType {
    REQUEST_CRUNCHYROLL_HISTORY,
    STORE_CRUNCHYROLL_HISTORY,
    ERROR_CRUNCHYROLL_HISTORY,

    REQUEST_CRUNCHYROLL_SESSION,
    STORE_CRUNCHYROLL_SESSION,

    REQUEST_TRAKT_SEARCH,
    STORE_TRAKT_SEARCH,

    REQUEST_TRAKT_EPISODE_HISTORY,
    STORE_TRAKT_EPISODE_HISTORY,

    START_TRAKT_EPISODE_HISTORY_ADD,
    SUCCESS_TRAKT_EPISODE_HISTORY_ADD,
    ERROR_TRAKT_EPISODE_HISTORY_ADD,

    TRAKT_USER_LOGGED_IN,
    TRAKT_USER_LOGGED_OUT
}